format_version: v1.0
type: UniqueComponent
attributes: {id: dacc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DACC_CHER_CH0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: dacc}
