package:
  format-version: "1.0.0"
  name: "csp_apps_sam_rh707"
  version: "v3.3.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.23.0"
