format_version: v1.0
type: UniqueComponent
attributes: {id: adc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: ADC_15_CGR_GAIN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADC_15_CHER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ADC_15_COR_OFFSET}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADC_15_IER_EOC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: ADC_15_NAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: ADC_15_NEG_INP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: ADC_15_POS_INP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: ADC_CLK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '2500000'}
  - type: Comment
    attributes: {id: ADC_CONV_TIME}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Conversion Time is 8.4 us ****'}
  - type: Comment
    attributes: {id: ADC_PRESCAL_WARNING}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: 'ADC Frequency < 200,000 Hz. Decrease prescaler value. '}
  - type: KeyValueSet
    attributes: {id: ADC_TRGR_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: adc}
